application: hegemonicas
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.2"

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /img
  static_dir: img

- url: /.*
  script: main.app

